# Generated by Django 5.1.6 on 2025-04-19 12:11

from django.db import migrations


def update_document_icons(apps, schema_editor):
    """
    Update all document type icons from fa-file-alt to fa-file-lines
    This improves visibility on white backgrounds
    """
    # Get the models
    WorkItemType = apps.get_model('workspace', 'WorkItemType')
    
    # Update all document types with the new icon
    WorkItemType.objects.filter(icon='fa-file-alt').update(icon='fa-file-lines')

    # Also update any with name similar to 'document' or 'doc'
    WorkItemType.objects.filter(name__icontains='document').update(icon='fa-file-lines')
    WorkItemType.objects.filter(name__icontains='doc').update(icon='fa-file-lines')


class Migration(migrations.Migration):

    dependencies = [
        # Reference the actual last migration in the workspace app
        ('workspace', '0003_alter_workitem_type_workitemtype_workitem_item_type'),
    ]

    operations = [
        migrations.RunPython(update_document_icons),
    ]
