# Generated by Django 4.2.20 on 2025-03-29 04:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlowChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('reflection', 'Team Reflection'), ('ideation', 'Idea Generation'), ('learning', 'Learning & Growth'), ('documentation', 'Documentation'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_frequency', models.CharField(choices=[('daily', 'Once per day'), ('workday', 'Once per workday'), ('weekly', 'Once per week'), ('biweekly', 'Twice per week'), ('custom', 'Custom schedule')], default='daily', max_length=20)),
                ('delivery_time', models.TimeField(default='09:00:00')),
                ('custom_days', models.CharField(default='12345', help_text='Days to deliver (1=Mon, 7=Sun)', max_length=20)),
                ('min_response_interval', models.DurationField(default=datetime.timedelta(seconds=14400), help_text='Minimum time between responses to encourage thoughtfulness')),
                ('reflection_prompts', models.TextField(blank=True, help_text='Optional prompts to guide discussion (one per line)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_slow_channels', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='slow_channels', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slow_channels', to='workspace.workitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='share_read_receipts',
            field=models.BooleanField(default=True, help_text='Share read receipts with message authors'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='show_online_status',
            field=models.BooleanField(default=False, help_text='Show your online status to other users'),
        ),
        migrations.CreateModel(
            name='SlowChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('scheduled_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('prompt', models.CharField(blank=True, max_length=255)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workspace.slowchannel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='workspace.slowchannelmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slow_channel_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('scheduling_note', models.CharField(blank=True, help_text='Optional note about why you chose this time', max_length=255)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_replies', to='workspace.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='workspace.thread')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='workspace.workitem')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('read_duration', models.DurationField(blank=True, help_text='How long the user spent viewing this message', null=True)),
                ('has_responded', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='workspace.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['read_at'],
                'unique_together': {('message', 'user')},
            },
        ),
    ]
