# Generated by Django 5.1.6 on 2025-04-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_update_document_icons'),
        ('workspace', 'update_document_icons'),
    ]

    operations = [
    ]
