# Generated by Django 4.2.20 on 2025-03-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('doc', 'Document'), ('project', 'Project')], max_length=20),
        ),
    ]
