# Generated by Django 5.1.6 on 2025-04-19 12:36

from django.db import migrations


def update_document_colors(apps, schema_editor):
    """
    Update all document type colors to ensure good visibility on all backgrounds
    This improves contrast and accessibility
    """
    # Get the models
    WorkItemType = apps.get_model('workspace', 'WorkItemType')
    
    # Update document types with better contrast colors
    WorkItemType.objects.filter(name__icontains='document').update(color='dark text-white', icon='fa-file-lines')
    WorkItemType.objects.filter(name__icontains='doc').update(color='dark text-white', icon='fa-file-lines')
    
    # Update warning colors to have dark text
    WorkItemType.objects.filter(color='warning').update(color='warning text-dark')
    
    # Update info colors to have dark text
    WorkItemType.objects.filter(color='info').update(color='info text-dark')
    
    # Update other colors to ensure they have proper text color
    WorkItemType.objects.filter(color='primary').update(color='primary text-white')
    WorkItemType.objects.filter(color='secondary').update(color='secondary text-white')
    WorkItemType.objects.filter(color='success').update(color='success text-white')
    WorkItemType.objects.filter(color='danger').update(color='danger text-white')
    
    print("Document colors and icons updated for better visibility and contrast")


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_merge_20250419_1744'),
    ]

    operations = [
        migrations.RunPython(update_document_colors),
    ]
