# Generated by Django 4.2.20 on 2025-03-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_slowchannel_message_is_scheduled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowchannel',
            name='custom_days',
            field=models.CharField(default='12345', help_text='Days to deliver (1=Mon, 7=Sun)', max_length=100),
        ),
    ]
