# Generated by Django 5.1.6 on 2025-04-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_update_document_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_from_websocket',
            field=models.BooleanField(default=False),
        ),
    ]
