# Generated by Django 4.2.20 on 2025-03-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_slowchannel_custom_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='auto_away_after',
            field=models.IntegerField(default=30, help_text='Set away status after inactive for this many minutes'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='away_message',
            field=models.CharField(blank=True, help_text="Message to show when you're away", max_length=255),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='away_mode',
            field=models.BooleanField(default=False, help_text='Enable away from keyboard mode'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='break_frequency',
            field=models.IntegerField(default=60, help_text='Reminder frequency in minutes to take breaks'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='lunch_break_duration',
            field=models.IntegerField(default=60, help_text='Duration of lunch break in minutes'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='lunch_break_start',
            field=models.TimeField(blank=True, help_text='Start time of your lunch break', null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='share_working_hours',
            field=models.BooleanField(default=True, help_text='Allow others to see your working hours'),
        ),
    ]
