# Generated by Django 4.2.20 on 2025-03-28 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnd_enabled', models.BooleanField(default=False)),
                ('dnd_start_time', models.TimeField(blank=True, null=True)),
                ('dnd_end_time', models.TimeField(blank=True, null=True)),
                ('work_days', models.CharField(default='12345', help_text='Days of week (1-7, where 1 is Monday)', max_length=20)),
                ('work_start_time', models.TimeField(default='09:00')),
                ('work_end_time', models.TimeField(default='17:00')),
                ('notification_mode', models.CharField(choices=[('all', 'All Notifications'), ('mentions', 'Mentions Only'), ('none', 'None')], default='all', max_length=10)),
                ('muted_channels', models.ManyToManyField(blank=True, related_name='muted_by_users', to='workspace.workitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
