# Generated by Django 4.2.20 on 2025-04-02 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0006_notificationpreference_muted_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='focus_mode',
            field=models.BooleanField(default=False, help_text='When enabled, only receive notifications from selected users and work items'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='focus_users',
            field=models.ManyToManyField(blank=True, help_text='Only receive notifications from these users when in focus mode', related_name='focus_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='focus_work_items',
            field=models.ManyToManyField(blank=True, help_text='Only receive notifications from these work items when in focus mode', related_name='focus_notifications', to='workspace.workitem'),
        ),
    ]
