# Generated by Django 4.2.20 on 2025-03-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_threadgroup_remove_message_is_thread_starter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_thread_starter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='workspace.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='workspace.thread'),
        ),
    ]
