# Generated by Django 4.2.20 on 2025-04-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_useronlinestatus_user'),
        ('workspace', '0008_notification_thread'),
    ]

    operations = [
    ]
