# Generated by Django 4.2.20 on 2025-04-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_user_online_status'),
        ('workspace', '0009_merge_20250402_0902'),
    ]

    operations = [
    ]
